# permissions for end users to view reloader.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reloader
    app.kubernetes.io/managed-by: kustomize
  name: reloader-viewer-role
rules:
- apiGroups:
  - reloader.external-secrets.io
  resources:
  - config
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reloader.external-secrets.io
  resources:
  - config/status
  verbs:
  - get
