---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reloader.external-secrets.io
  resources:
  - configs
  - configs/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reloader.external-secrets.io
  resources:
  - configs/finalizers
  verbs:
  - update
