{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "reloader.fullname" . }}
  namespace: {{ template "reloader.namespace" . }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    kind: {{ .Values.certificate.issuer.kind }}
    name: {{ .Values.certificate.issuer.name }}
    namespace: {{ .Values.certificate.issuer.namespace }}
  dnsNames:
{{- range .Values.certificate.hosts }}
  - {{ . | quote }}
{{- end }}
{{- end }}
