{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "reloader.fullname" . }}
  namespace: {{ template "reloader.namespace" . }}
  labels:
    {{- include "reloader.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.podMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  jobLabel: {{ include "reloader.fullname" . }}
  selector:
    matchLabels:
      {{- include "reloader.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: {{ .Values.podMonitor.path }}
      interval: {{ .Values.podMonitor.interval }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.podMonitor.honorLabels }}
{{- end }}
