{{- if .Values.service.socket.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reloader.fullname" . }}-socket
  namespace: {{ template "reloader.namespace" . }}
  labels:
    {{- include "reloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.socket.type }}
  ports:
  - name: sock
    port: {{ .Values.service.socket.port}}
    protocol: TCP
    targetPort: {{ .Values.service.socket.targetPort}}
  selector:
    {{- include "reloader.selectorLabels" . | nindent 4 }}
{{- end }}