apiVersion: v1
kind: Service
metadata:
  name: {{ include "reloader.fullname" . }}
  namespace: {{ template "reloader.namespace" . }}
  labels:
    {{- include "reloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reloader.selectorLabels" . | nindent 4 }}
