name: lint-and-test

on:
  pull_request:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      - name: Test
        run: make test

  go-lint:
    name: Lint Golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      - name: Lint
        run: make lint
